#! /usr/bin/python
###
do=True
try:
	import os 
	import sys
	sys.dont_write_bytecode = True
	import platform
	from PySide import QtGui
except ImportError:
	print("Error : Some modules are missing")
	do=False
try:
	from duck_launcher import Main
except ImportError:
	print("Error : Some files are missing... Try to reinstall Duck Launcher from a trusted source.")
	do =False

version = platform.python_version()
if "2.7" not in version:
	do=False
	print("Sorry, you need python 2.7 to run Duck Launcher")
#check if there is already Duck Launcher...launched
import wnck 
screen = wnck.screen_get_default()
screen.force_update()
win = screen.get_windows()
for w in win:
	if "ducklauncher!!" in w.get_name():
		do=False 

if do==True:
	print("Welcome to Duck Launcher !")
	app = QtGui.QApplication(sys.argv)
	win = Main.Launcher()
	win.show()
	win.raise_()
	sys.exit(app.exec_())
elif do==False:
	print("Quiting Duck Launcher")
